import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })


import "/assets/css/all.min.css"
{/* <!-- bootstrap --> */}
import"/assets/bootstrap/css/bootstrap.min.css"
{/* <!-- owl carousel --> */}
import"/assets/css/owl.carousel.css"
{/* <!-- magnific popup --> */}
import"/assets/css/magnific-popup.css"
{/* <!-- animate css --> */}
import"/assets/css/animate.css"
{/* <!-- mean menu css --> */}
import"/assets/css/meanmenu.min.css"
{/* <!-- main style --> */}
import"/assets/css/main.css"
{/* <!-- responsive --> */}
import"/assets/css/responsive.css"

import Navbar from './(components)/footer/navbar/navbar'
import Footer from './(components)/footer/footer'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
      
    </html>
  )
}
